const S = { user: null, view: 'landing', adminView: 'dashboard', search: null, results: [], booking: { vehicle: null, seats: [], food: [], undoStack: [] }, bookingTab: 'upcoming', menuTab: 'main', foodQueue: [], sortBy: 'price', filterType: 'all', modal: null, mapInstance: null };
function fmtDur(m) { const h = Math.floor(m / 60), r = m % 60; return h ? (r ? `${h}h ${r}m` : `${h}h`) : `${r}m`; }
function fmtDate(s) { if (!s) return ''; const d = new Date(s); return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }); }
function fmtMoney(n) { return '₹' + Number(n).toLocaleString('en-IN'); }
function toast(msg, type = 'success') { const t = document.getElementById('toast'); t.className = `toast toast-${type}`; t.querySelector('.toast-icon').textContent = type === 'success' ? '✓' : '✕'; document.getElementById('toast-msg').textContent = msg; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 3000); }
function navigate(view, data = {}) { S.view = view; if (data.adminView) S.adminView = data.adminView; window.scrollTo(0, 0); render(); }

const CITY_COORDS = {
    'Mumbai': [19.0760, 72.8777], 'Pune': [18.5204, 73.8567], 'Nashik': [19.9975, 73.7898],
    'Nagpur': [21.1458, 79.0882], 'Delhi': [28.6139, 77.2090], 'Bangalore': [12.9716, 77.5946],
    'Hyderabad': [17.3850, 78.4867], 'Chennai': [13.0827, 80.2707], 'Kolkata': [22.5726, 88.3639],
    'Jaipur': [26.9124, 75.7873], 'Ahmedabad': [23.0225, 72.5714], 'Lucknow': [26.8467, 80.9462],
    'Bhopal': [23.2599, 77.4126], 'Surat': [21.1702, 72.8311], 'Indore': [22.7196, 75.8577]
};

function renderMap(fromCity, toCity, via = []) { 
    const mapDiv = document.getElementById('google-map'); 
    if (!mapDiv || typeof L === 'undefined') return; 

    if (S.mapInstance) { S.mapInstance.remove(); S.mapInstance = null; }

    const map = L.map(mapDiv, { zoomControl: false, attributionControl: false }).setView([22.5937, 78.9629], 5);
    S.mapInstance = map;

    L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
        maxZoom: 19
    }).addTo(map);

    if (fromCity && toCity) {
        const stops = [fromCity, ...(via || []), toCity];
        const points = stops.map(c => CITY_COORDS[c]).filter(Boolean);
        
        if (points.length > 1) {
            points.forEach((p, i) => {
                L.circleMarker(p, { 
                    radius: i === 0 || i === points.length - 1 ? 7 : 5, 
                    color: '#1a3f7a', fillColor: '#b5680a', fillOpacity: 1, weight: 2 
                }).addTo(map).bindPopup(stops[i]);
            });
            const line = L.polyline(points, { color: '#1a3f7a', weight: 3, dashArray: '5, 10' }).addTo(map);
            map.fitBounds(line.getBounds(), { padding: [40, 40] });
        }
    } else {
        Object.entries(CITY_COORDS).forEach(([name, pos]) => {
            L.circleMarker(pos, { radius: 4, color: '#b5680a', fillOpacity: 0.6, weight: 1 }).addTo(map).bindTooltip(name);
        });
    }
}
function renderNav() { const u = S.user; let right = ''; if (!u) { right = `<button class="nav-btn nav-btn-outline" onclick="navigate('login')">Login</button><button class="nav-btn nav-btn-primary" onclick="navigate('signup')">Sign Up</button>`; } else if (u.role === 'admin') { right = `<div class="nav-user-group"><span class="nav-user-role">Admin</span><span class="nav-user-name">${u.name}</span><div class="nav-avatar" onclick="logout()">${u.name[0]}</div></div>`; } else { right = `<div class="nav-user-group"><button class="nav-link" onclick="navigate('my-bookings')">My Bookings</button><div class="nav-avatar" title="Click to sign out" onclick="logout()">${u.name[0]}</div></div>`; } let adminL = u && u.role === 'admin' ? `<button class="nav-link ${S.view === 'admin' ? 'active' : ''}" onclick="navigate('admin',{adminView:'dashboard'})">Admin Panel</button>` : ''; return `<nav class="nav"><div class="nav-logo" onclick="navigate(${u && u.role === 'admin' ? `'admin'` : `'landing'`})"><div class="nav-logo-icon">🚄</div><span class="nav-logo-text">RailRoute</span></div><div class="nav-links">${u && u.role !== 'admin' ? `<button class="nav-link" onclick="navigate('landing')">Home</button>` : ''}${adminL}</div><div style="display:flex;align-items:center;gap:8px">${right}</div></nav>`; }
const VIEWS = { 'landing': () => viewLanding(), 'login': () => viewLogin(), 'signup': () => viewSignup(), 'search-results': () => viewSearchResults(), 'seat-selection': () => viewSeatSelection(), 'food-order': () => viewFoodOrder(), 'booking-confirmed': () => viewBookingConfirmed(), 'my-bookings': () => viewMyBookings(), 'admin': () => viewAdmin() };
function render() { const fn = VIEWS[S.view] || VIEWS['landing']; document.getElementById('root').innerHTML = fn(); if (S.view === 'search-results' && S.search) { renderMap(S.search.from, S.search.to); } else if (S.view === 'landing') { renderMap(); } }
function login(email, pass) { const u = DB.find('users', u => u.email === email && u.password === pass && u.active !== false); if (!u) return false; S.user = u; localStorage.setItem('rr_session', u.id); return u; }
function logout() { S.user = null; localStorage.removeItem('rr_session'); navigate('landing'); }
function restoreSession() { const id = localStorage.getItem('rr_session'); if (id) S.user = DB.find('users', u => u.id === id) || null; }
function guard(role = 'user') { if (!S.user) { navigate('login'); return false; } if (role === 'admin' && S.user.role !== 'admin') { navigate('landing'); return false; } return true; }
function viewLogin() { return `${renderNav()}<div class="page"><div class="auth-page"><div class="auth-card"><div class="auth-logo"><div class="auth-logo-icon">🚄</div><span class="auth-logo-text">RailRoute</span></div><div class="auth-title">Welcome back</div><div class="auth-sub">Sign in to your account to continue</div><div class="auth-form"><div class="form-group"><label class="form-label">Email</label><input class="form-input" type="email" id="l-email" placeholder="you@example.com"></div><div class="form-group"><label class="form-label">Password</label><input class="form-input" type="password" id="l-pass" placeholder="••••••••" onkeydown="if(event.key==='Enter')handleLogin()"><div class="form-error" id="l-err"></div></div><button class="btn btn-primary btn-full" onclick="handleLogin()">Sign In →</button></div><div class="auth-switch">No account? <span onclick="navigate('signup')">Sign up free</span></div></div></div></div>`; }
function handleLogin() { const email = document.getElementById('l-email').value.trim(), pass = document.getElementById('l-pass').value, err = document.getElementById('l-err'), u = login(email, pass); if (!u) { err.textContent = 'Invalid email or password'; err.classList.add('show'); return; } toast('Welcome back, ' + u.name + '!'); if (u.role === 'admin') navigate('admin'); else if (S.search) navigate('search-results'); else navigate('landing'); }
function viewSignup() { return `${renderNav()}<div class="page"><div class="auth-page"><div class="auth-card"><div class="auth-logo"><div class="auth-logo-icon">🚄</div><span class="auth-logo-text">RailRoute</span></div><div class="auth-title">Create account</div><div class="auth-sub">Join RailRoute and travel smarter</div><div class="auth-form"><div class="form-group"><label class="form-label">Full Name</label><input class="form-input" type="text" id="r-name" placeholder="Name"></div><div class="form-group"><label class="form-label">Email</label><input class="form-input" type="email" id="r-email" placeholder="you@example.com"><div class="form-error" id="r-err"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Password</label><input class="form-input" type="password" id="r-pass" placeholder="••••••••"></div><div class="form-group"><label class="form-label">Confirm</label><input class="form-input" type="password" id="r-pass2" placeholder="••••••••"></div></div><button class="btn btn-primary btn-full" onclick="handleSignup()">Create Account →</button></div><div class="auth-switch">Already registered? <span onclick="navigate('login')">Sign in</span></div></div></div></div>`; }
function handleSignup() { const name = document.getElementById('r-name').value.trim(), email = document.getElementById('r-email').value.trim(), pass = document.getElementById('r-pass').value, pass2 = document.getElementById('r-pass2').value, err = document.getElementById('r-err'); if (!name || !email || !pass) { err.textContent = 'All fields required'; err.classList.add('show'); return; } if (pass !== pass2) { err.textContent = 'Passwords do not match'; err.classList.add('show'); return; } if (DB.find('users', u => u.email === email)) { err.textContent = 'Email already registered'; err.classList.add('show'); return; } const nu = { id: uid(), name, email, password: pass, role: 'user', createdAt: new Date().toISOString().split('T')[0], active: true }; DB.add('users', nu); login(email, pass); toast('Account created! Welcome, ' + name + '!'); navigate('landing'); }
function doSearch(from, to, date) { 
    const isMatch = (v) => {
        const stops = [v.from, ...(v.via || []), v.to];
        const fromIdx = stops.indexOf(from);
        const toIdx = stops.indexOf(to);
        return fromIdx !== -1 && toIdx !== -1 && fromIdx < toIdx;
    };
    const trains = DB.filter('trains', isMatch).map(t => ({ ...t, vtype: 'train' }));
    const buses = DB.filter('buses', isMatch).map(b => ({ ...b, vtype: 'bus' }));
    const flights = DB.filter('airplanes', isMatch).map(f => ({ ...f, vtype: 'airplane' }));

    return [...trains, ...buses, ...flights];
}

function sortResults(list) { return [...list].sort((a, b) => { if (S.sortBy === 'price') return a.price - b.price; if (S.sortBy === 'time') return a.duration - b.duration; if (S.sortBy === 'safety') return b.safety - a.safety; return 0; }); }
function viewLanding() {
  const cities = DB.get('cities');
  const cityOpts = cities.map(c => `<option>${c}</option>`).join('');
  const today = new Date().toISOString().split('T')[0];
  return `${renderNav()}<div class="page"><section class="hero"><div class="hero-bg"></div><div class="hero-content"><div><div class="hero-eyebrow"><span class="hero-eyebrow-dot"></span>Smart Travel Booking · DSA Project</div><h1><span class="h1-gold">Rail</span><span class="h1-blue">Route</span></h1><p class="hero-sub">Book train and bus tickets instantly. Compare routes by <strong>cost, time & safety</strong>. Every feature is powered by a real data structure or algorithm.</p><div class="hero-stats"><div class="hero-stat"><div class="hs-num">${DB.get('trains').length + DB.get('buses').length}+</div><div class="hs-label">Routes</div></div><div class="hero-stat"><div class="hs-num">${DB.get('cities').length}</div><div class="hs-label">Cities</div></div><div class="hs-stat"><div class="hs-num">12</div><div class="hs-label">DSA Concepts</div></div></div></div><div class="search-card"><div class="search-card-title">🔍 Find Your Route</div><div class="search-form"><div class="form-row"><div class="form-group"><label class="form-label">From</label><select class="form-input" id="sc-from"><option value="">Select city</option>${cityOpts}</select></div><div class="form-group"><label class="form-label">To</label><select class="form-input" id="sc-to"><option value="">Select city</option>${cityOpts}</select></div></div><div class="form-row"><div class="form-group"><label class="form-label">Date</label><input class="form-input" type="date" id="sc-date" value="${today}" min="${today}"></div><div class="form-group"><label class="form-label">Passengers</label><select class="form-input" id="sc-pass"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></div></div><button class="btn btn-primary btn-full" onclick="handleSearch()">Search Routes →</button></div></div></div></section></div>`;
}

function getRealDistance(from,to){
    return new Promise((res)=>{
        if (typeof google === 'undefined' || !google.maps) return res(null);
        const timeout = setTimeout(() => res(null), 5000);
        const svc = new google.maps.DistanceMatrixService();
        svc.getDistanceMatrix({
            origins:[from+", India"],
            destinations:[to+", India"],
            travelMode: google.maps.TravelMode.DRIVING
        },(resp,status)=>{
            clearTimeout(timeout);
            if(status==='OK' && resp.rows[0].elements[0].status==='OK'){
                const e=resp.rows[0].elements[0];
                res({distance:e.distance.text,duration:e.duration.text});
            } else {
                res(null);
            }
        });
    });
}
async function handleSearch(){const btn=document.querySelector('.search-card .btn-primary');if(!btn)return;const originalText=btn.textContent;const from=document.getElementById('sc-from').value;const to=document.getElementById('sc-to').value;const date=document.getElementById('sc-date').value;if(!from||!to)return toast('Please select origin and destination','error');if(from===to)return toast('Origin and destination cannot be the same','error');btn.textContent='Searching...';btn.disabled=true;let results=doSearch(from,to,date);try{const matrixData=await getRealDistance(from,to);if(matrixData){S.matrixData=matrixData;results=results.map(v=>({...v,realDistance:matrixData.distance}));}}catch(e){console.warn('Distance API failed, using local data',e);}finally{btn.textContent=originalText;btn.disabled=false;}S.search={from,to,date};S.results=results;S.sortBy='price';if(!S.user)return navigate('login');navigate('search-results');}
function viewSearchResults(){if(!guard())return'';if(!S.search){navigate('landing');return'';}const{from,to,date}=S.search;const results=sortResults(S.results);const tabs=['price','time','safety'].map(s=>`<button class="sort-tab ${S.sortBy===s?'active':''}" onclick="setSortBy('${s}')">${s==='price'?'💰 Price':s==='time'?'⚡ Fastest':'🛡 Safety'}</button>`).join('');const cards=results.length?results.map((v,i)=>vehicleCard(v,i===0)).join(''):`<div class="empty-state"><div class="empty-icon">😕</div><div class="empty-title">No routes found</div><p>Try different cities or check back later.</p><button class="btn btn-primary" style="margin-top:16px" onclick="navigate('landing')">Modify Search</button></div>`;const liveStats=S.matrixData?`<span class="tag tag-blue">Live Map Data: ${S.matrixData.distance} · ${S.matrixData.duration}</span>`:'';return`${renderNav()}<div class="page results-page"><div class="results-header"><div class="container"><div class="results-header-inner"><div class="route-badge"><span class="rb-city">${from}</span><span class="rb-arrow">→</span><span class="rb-city">${to}</span><span class="rb-date">📅 ${fmtDate(date)}</span></div><span class="tag tag-teal">${results.length} routes</span>${liveStats}<div class="sort-tabs">${tabs}</div></div></div></div><div class="container" style="padding-top:20px;display:grid;grid-template-columns:1fr 350px;gap:24px"><div class="results-grid">${cards}</div><div><div id="google-map" style="width:100%;height:400px;border-radius:var(--r2);border:1.5px solid var(--border);position:sticky;top:150px"></div></div></div></div>`;}
function vehicleCard(v, isBest) {
    const typeMap = { express: 'Express', superfast: 'Superfast', regular: 'Regular', 'bus-ac': 'AC Bus', 'bus-normal': 'Bus', 'flight-economy': 'Economy', 'flight-business': 'Business' };
    const via = v.via && v.via.length ? `via ${v.via.slice(0, 2).join(', ')}` : 'Direct';
    let icon = '';
    if (v.vtype === 'train') icon = '🚄';
    else if (v.vtype === 'bus') icon = '🚌';
    else if (v.vtype === 'airplane') icon = '✈️';

    const bookButton = `<button class="btn btn-primary btn-sm" onclick="selectVehicle('${v.id}','${v.vtype}')">Book Seats →</button>`;

    return `<div class="vehicle-card type-${v.type}">${isBest ? '<div class="best-tag">✦ Best Value</div>' : ''}<div><div class="vc-badge badge-${v.type}">${icon} ${typeMap[v.type] || v.type}</div><div class="vc-name">${v.name}</div><div class="vc-number">${v.number}</div><div class="vc-timing"><div><div class="vc-time">${v.dep}</div><div style="font-size:11px;color:var(--muted)">${v.from}</div></div><div class="vc-duration"><div class="vc-dur-line"></div><div class="vc-dur-text">${fmtDur(v.duration)}</div></div><div><div class="vc-time">${v.arr}</div><div style="font-size:11px;color:var(--muted)">${v.to}</div></div></div><div class="vc-stops">🛑 ${via}</div><div class="vc-meta"><div class="vc-meta-item">🛡 Safety <span class="mval">${v.safety}/10</span></div><div class="vc-meta-item">💺 <span class="mval">${Math.floor(v.seats * 0.6)} avail</span></div></div></div><div class="vc-right"><div><div class="vc-price">${fmtMoney(v.price)}</div><div class="vc-price-label">per person</div></div>${bookButton}</div></div>`;
}
function setSortBy(by) { S.sortBy = by; render(); }
function selectVehicle(id, vtype) {
    const v = vtype === 'train' ? DB.find('trains', t => t.id === id) : vtype === 'bus' ? DB.find('buses', b => b.id === id) : DB.find('airplanes', a => a.id === id);
    S.booking = { vehicle: v, vtype, seats: [], food: [], undoStack: [] };
    S.seatLayout = genSeats(id, S.search.date, v.seats);
    navigate('seat-selection');
}
function pseudoRand(seed, max) { let h = 0; for (let i = 0; i < seed.length; i++) { h = (h << 5) - h + seed.charCodeAt(i); h |= 0; } return Math.abs(h) % max; }
function genSeats(vehicleId, date, total) { const rows = Math.ceil(total / 8); const layout = []; for (let r = 0; r < rows; r++) { const row = []; for (let c = 0; c < 9; c++) { if (c === 4) { row.push('gap'); continue; } const seat = `${String.fromCharCode(65 + r)}${c < 4 ? c + 1 : c}`; const taken = pseudoRand(vehicleId + date + seat, 3) === 0; row.push({ id: seat, state: taken ? 'tk' : 'av' }); } layout.push(row); } return layout; }
function viewSeatSelection() { if (!guard()) return ''; const { vehicle: v, vtype, seats } = S.booking; if (!v) { navigate('search-results'); return ''; } const grid = S.seatLayout.map(row => row.map(cell => { if (cell === 'gap') return `<div class="s gap"></div>`; const sel = seats.includes(cell.id); return `<div class="s ${sel ? 'me' : cell.state}" onclick="toggleSeat('${cell.id}')" title="${cell.id}">${cell.id}</div>`; }).join('')).join(''); const total = seats.length * v.price; const seatTags = seats.map(s => `<span class="bs-seat-tag">${s}</span>`).join('') || '<span style="color:var(--muted2);font-size:13px">No seats selected yet</span>'; return `${renderNav()}<div class="page seat-page"><div class="container"><div style="margin-bottom:20px"><button class="btn btn-secondary btn-sm" onclick="navigate('search-results')">← Back to Results</button></div><div class="booking-layout"><div><div class="seat-section-card"><div style="font-family:'Playfair Display',serif;font-size:19px;font-weight:800;margin-bottom:5px;color:var(--cream)">${v.name}</div><div style="font-size:13px;color:var(--muted);margin-bottom:18px">${v.number} · ${v.from} → ${v.to} · ${v.dep}–${v.arr}</div><div class="seat-legend"><div class="sl-item"><div class="sl-dot sl-av"></div>Available</div><div class="sl-item"><div class="sl-dot sl-tk"></div>Booked</div><div class="sl-item"><div class="sl-dot sl-me"></div>Selected</div></div><div class="comp-label">Compartment 1 — Click a seat to select</div><div class="seat-grid">${grid}</div></div></div><div class="booking-summary"><div class="bs-title">Booking Summary</div><div class="bs-section"><div class="bs-label">Route</div><div class="bs-value">${v.from} → ${v.to}</div></div><div class="bs-section"><div class="bs-label">Date & Time</div><div class="bs-value">${fmtDate(S.search.date)} · ${v.dep}–${v.arr}</div></div><div class="bs-section"><div class="bs-label">Selected Seats (${seats.length})</div><div class="bs-seats">${seatTags}</div></div><button class="undo-btn" onclick="undoSeat()">↩ Undo last selection</button><div class="bs-section"><div class="bs-label">Base Fare</div><div class="bs-total">${fmtMoney(total)}</div></div><button class="btn btn-primary btn-full" ${seats.length === 0 ? 'disabled style="opacity:0.45;cursor:not-allowed"' : ''} onclick="proceedToFood()">Continue to Food →</button><button class="btn btn-secondary btn-full" style="margin-top:8px" onclick="proceedToFood(true)">Skip Food & Confirm</button></div></div></div></div>`; }
function toggleSeat(id) { const layout = S.seatLayout; let found = null; for (let r of layout) { for (let c of r) { if (c !== 'gap' && c.id === id) { found = c; break; } } if (found) break; } if (!found || found.state === 'tk') return; S.booking.undoStack.push([...S.booking.seats]); if (S.booking.seats.includes(id)) S.booking.seats = S.booking.seats.filter(s => s !== id); else S.booking.seats.push(id); render(); }
function undoSeat() { if (S.booking.undoStack.length === 0) return toast('Nothing to undo', 'error'); S.booking.seats = S.booking.undoStack.pop(); toast('Selection undone ↩'); render(); }
function proceedToFood(skip = false) { if (S.booking.seats.length === 0) return toast('Please select at least one seat', 'error'); if (skip) { confirmBooking(true); return; } navigate('food-order'); }
function confirmBooking(skipFood = false) { if (skipFood) S.booking.food = []; const { vehicle: v, vtype, seats, food } = S.booking; const date = S.search.date; const baseCost = seats.length * v.price, foodCost = food.reduce((s, i) => s + i.price, 0), total = baseCost + foodCost; const b = { id: 'BK' + Date.now().toString(36).toUpperCase(), userId: S.user.id, vehicleId: v.id, vehicleType: vtype, vehicleName: v.name, from: v.from, to: v.to, date, dep: v.dep, arr: v.arr, seats, foodOrders: food, baseCost, foodCost, total, status: 'confirmed', bookedAt: new Date().toISOString().split('T')[0] }; DB.add('bookings', b); S.lastBooking = b; toast('🎉 Booking confirmed!'); navigate('booking-confirmed'); }
function viewBookingConfirmed() { if (!guard()) return ''; const b = S.lastBooking; if (!b) { navigate('my-bookings'); return ''; } const foodList = b.foodOrders.length ? b.foodOrders.map(f => `<div style="font-size:13px;padding:4px 0;color:var(--muted)">${f.icon || '🍽️'} ${f.name} — <span style="color:var(--gold);font-weight:700">${fmtMoney(f.price)}</span></div>`).join('') : '<div style="font-size:13px;color:var(--muted2)">No food ordered</div>'; const seats = b.seats.map(s => `<span class="ticket-seat">${s}</span>`).join(''); return `${renderNav()}<div class="page confirm-page"><div class="container"><div class="ticket-card"><div class="ticket-header"><div class="ticket-header-content"><div class="ticket-status">● CONFIRMED</div><div class="ticket-id">Booking ID: ${b.id}</div><div class="ticket-route">${b.from} → ${b.to}</div></div></div><div class="ticket-body"><div><div class="ticket-section-title">Journey Details</div><div class="ticket-detail"><div class="td-label">Vehicle</div><div class="td-value">${b.vehicleName}</div></div><div class="ticket-detail"><div class="td-label">Date</div><div class="td-value">${fmtDate(b.date)}</div></div><div class="ticket-detail"><div class="td-label">Departure</div><div class="td-value">${b.dep}</div></div><div class="ticket-detail"><div class="td-label">Arrival</div><div class="td-value">${b.arr}</div></div><div class="ticket-detail"><div class="td-label">Passenger</div><div class="td-value">${S.user.name}</div></div></div><div><div class="ticket-section-title">Seats Reserved</div><div class="ticket-seats">${seats}</div><div style="margin-top:20px"><div class="ticket-section-title">Food Orders</div>${foodList}</div></div></div><div class="ticket-divider"></div><div class="ticket-footer"><div><div style="font-size:12px;color:var(--muted);margin-bottom:4px">Total Paid</div><div class="ticket-total">${fmtMoney(b.total)}</div></div><div class="ticket-qr">🎫</div></div></div><div class="confirm-actions"><button class="btn btn-primary" onclick="navigate('my-bookings')">View My Bookings</button><button class="btn btn-secondary" onclick="navigate('landing')">Book Another</button></div></div></div>`; }
function viewMyBookings() { if (!guard()) return ''; const tab = S.bookingTab || 'upcoming', today = new Date().toISOString().split('T')[0]; let bks = DB.filter('bookings', b => b.userId === S.user.id); if (tab === 'upcoming') bks = bks.filter(b => b.date >= today && b.status === 'confirmed'); else if (tab === 'past') bks = bks.filter(b => b.date < today || b.status === 'past'); else bks = bks.filter(b => b.status === 'cancelled'); const tabBtns = ['upcoming', 'past', 'cancelled'].map(t => `<button class="booking-tab ${tab === t ? 'active' : ''}" onclick="S.bookingTab='${t}';render()">${t.charAt(0).toUpperCase() + t.slice(1)}</button>`).join(''); const cards = bks.length ? bks.sort((a, b) => b.bookedAt.localeCompare(a.bookedAt)).map(b => `<div class="booking-item"><div><div class="bi-route">${b.from} → ${b.to}</div><div class="bi-meta">${b.vehicleName} · ${fmtDate(b.date)} · ${b.dep}–${b.arr}</div><div class="bi-tags"><span class="bi-tag">💺 ${b.seats.join(', ')}</span>${b.foodOrders.length ? `<span class="bi-tag">🍽️ ${b.foodOrders.length} item${b.foodOrders.length > 1 ? 's' : ''}</span>` : ''}<span class="bi-tag">📋 ${b.id}</span></div></div><div class="bi-right"><div class="bi-price">${fmtMoney(b.total)}</div><span class="bi-status status-${b.status}">${b.status === 'confirmed' ? '✓ Confirmed' : b.status === 'cancelled' ? '✕ Cancelled' : 'Past'}</span>${b.status === 'confirmed' && b.date >= today ? `<button class="btn btn-danger btn-sm" onclick="cancelBooking('${b.id}')">Cancel</button>` : ''}</div></div>`).join('') : `<div class="empty-state"><div class="empty-icon">🎫</div><div class="empty-title">No ${tab} bookings</div>${tab === 'upcoming' ? `<button class="btn btn-primary" style="margin-top:16px" onclick="navigate('landing')">Search Routes</button>` : ''}</div>`; return `${renderNav()}<div class="page bookings-page"><div class="container"><div class="sec-title" style="margin-bottom:6px">My Bookings</div><div class="sec-sub" style="margin-bottom:24px">All your trips in one place</div><div class="booking-tabs">${tabBtns}</div><div class="booking-list">${cards}</div></div></div>`; }
function cancelBooking(id) { DB.update('bookings', id, { status: 'cancelled' }); toast('Booking cancelled'); render(); }
function viewFoodOrder() { if (!guard()) return ''; const tab = S.menuTab, food = DB.filter('food', f => f.cat === tab), cart = S.booking.food, cartTotal = cart.reduce((s, i) => s + i.price, 0); const tabs = ['main', 'snacks', 'beverages'].map(t => `<button class="menu-tab ${tab === t ? 'active' : ''}" onclick="setMenuTab('${t}')">${t === 'main' ? '🍱 Mains' : t === 'snacks' ? '🥟 Snacks' : '☕ Beverages'}</button>`).join(''); const items = food.map(f => `<div class="menu-item"><div class="mi-icon">${f.icon}</div><div class="mi-name">${f.name}</div><div class="mi-desc">${f.desc}</div><div class="mi-footer"><div class="mi-price">${fmtMoney(f.price)}</div><button class="mi-add" onclick="addToCart('${f.id}')">+ Add</button></div></div>`).join(''); const cartItems = cart.length ? cart.map((item, i) => `<div class="cart-item"><span class="ci-name">${item.icon} ${item.name}</span><span class="ci-price">${fmtMoney(item.price)}</span><button class="ci-remove" onclick="removeFromCart(${i})">✕</button></div>`).join('') : '<div class="cart-empty">🍽️<br>Add items from the menu</div>'; const queueItems = cart.slice(0, 3).map((item, i) => `<div class="queue-item ${i === 0 ? 'qi-status-preparing' : ''}"><div class="qi-num">#0${i + 1}</div><div class="qi-info"><div class="qi-name">${item.name}</div><div class="qi-wait">${i === 0 ? '⏳ Preparing Now' : `⏳ ~${(i + 1) * 7} min`}</div></div></div>`).join(''); return `${renderNav()}<div class="page food-page"><div class="container"><div style="margin-bottom:20px;display:flex;align-items:center;justify-content:space-between"><button class="btn btn-secondary btn-sm" onclick="navigate('seat-selection')">← Back to Seats</button><span class="tag tag-gold">🚄 ${S.booking.vehicle.name}</span></div><div style="margin-bottom:20px"><div class="sec-title">Order Food 🍽️</div><div class="sec-sub">For your journey — processed first-come, first-served (Queue)</div></div><div class="food-layout"><div><div class="menu-tabs">${tabs}</div><div class="menu-items">${items}</div></div><div><div class="cart-card"><div class="cart-title">Your Order (${cart.length} items)</div>${cartItems}${cart.length ? `<div class="divider" style="margin:12px 0"></div><div style="display:flex;justify-content:space-between;margin-bottom:14px"><span style="font-size:13px;color:var(--muted)">Food Total</span><span style="font-weight:800;color:var(--gold)">${fmtMoney(cartTotal)}</span></div>${queueItems.length ? `<div class="queue-preview"><div class="qp-label">Order Queue Preview</div>${queueItems}</div>` : ''}` : ''}<button class="btn btn-primary btn-full" style="margin-top:14px" onclick="confirmBooking()">Confirm Booking →</button><button class="btn btn-secondary btn-full" style="margin-top:8px" onclick="confirmBooking(true)">Skip & Confirm</button></div></div></div></div></div>`; }
function setMenuTab(t) { S.menuTab = t; render(); }
function addToCart(fid) { const item = DB.find('food', f => f.id === fid); S.booking.food.push({ ...item }); toast(`${item.icon} ${item.name} added!`); render(); }
function removeFromCart(i) { S.booking.food.splice(i, 1); render(); }
function adminSidebar() { const links = [{ id: 'dashboard', icon: '📊', label: 'Dashboard' }, { id: 'trains', icon: '🚄', label: 'Trains & Buses' }, { id: 'stations', icon: '🏙️', label: 'Stations' }, { id: 'bookings', icon: '🎫', label: 'All Bookings' }, { id: 'users', icon: '👥', label: 'Users' }]; return `<div class="admin-sidebar"><div class="sidebar-label">Overview</div>${links.map(l => `<button class="sidebar-link ${S.adminView === l.id ? 'active' : ''}" onclick="S.adminView='${l.id}';render()"><span class="sl-icon">${l.icon}</span>${l.label}</button>`).join('')}<div class="divider"></div><button class="sidebar-link" onclick="logout()"><span class="sl-icon">🚪</span>Logout</button></div>`; }
function viewAdmin() { if (!guard('admin')) return ''; const main = { dashboard: adminDashboard, trains: adminTrains, stations: adminStations, bookings: adminBookings, users: adminUsers }[S.adminView] || adminDashboard; return `${renderNav()}<div class="page"><div class="admin-layout">${adminSidebar()}<div class="admin-main">${main()}</div></div></div>${S.modal ? renderModal() : ''}`; }
function adminDashboard() { const users = DB.get('users').filter(u => u.role === 'user').length; const bks = DB.get('bookings'); const rev = bks.filter(b => b.status !== 'cancelled').reduce((s, b) => s + b.total, 0); const vehicleCount = DB.get('trains').length + DB.get('buses').length + DB.get('airplanes').length; const recent = [...bks].sort((a, b) => b.bookedAt.localeCompare(a.bookedAt)).slice(0, 6); const rows = recent.map(b => { const u = DB.find('users', u => u.id === b.userId); return `<tr><td><code style="font-size:11px;color:var(--muted2)">${b.id}</code></td><td>${u ? u.name : 'Unknown'}</td><td>${b.from} → ${b.to}</td><td>${fmtDate(b.date)}</td><td style="font-weight:700">${fmtMoney(b.total)}</td><td><span class="bi-status status-${b.status}" style="font-size:10px">${b.status}</span></td></tr>`; }).join(''); return `<div class="admin-main-title">Dashboard</div><div class="admin-main-sub">Live system overview</div><div class="stats-grid"><div class="stat-card sc-gold"><div class="stat-icon">👥</div><div class="stat-num">${users}</div><div class="stat-label">Registered Users</div></div><div class="stat-card sc-blue"><div class="stat-icon">🎫</div><div class="stat-num">${bks.length}</div><div class="stat-label">Total Bookings</div></div><div class="stat-card sc-teal"><div class="stat-icon">💰</div><div class="stat-num">₹${(rev / 1000).toFixed(1)}k</div><div class="stat-label">Total Revenue</div></div><div class="stat-card sc-rose"><div class="stat-icon">🚄</div><div class="stat-num">${vehicleCount}</div><div class="stat-label">Vehicles</div></div></div><div class="admin-table-wrap"><div class="admin-table-header"><div class="admin-table-title">Recent Bookings</div></div><div style="overflow-x:auto"><table class="admin-table"><thead><tr><th>ID</th><th>User</th><th>Route</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></div>`; }
function adminTrains() { const all = [...DB.get('trains').map(t => ({ ...t, _kind: 'Train' })), ...DB.get('buses').map(b => ({ ...b, _kind: 'Bus' })), ...DB.get('airplanes').map(a => ({ ...a, _kind: 'Airplane' }))]; const rows = all.map(v => `<tr><td><span style="font-family:'JetBrains Mono',monospace;font-size:11px;font-weight:700">${v.number}</span></td><td><strong>${v.name}</strong><br><span style="font-size:11px;color:var(--muted2)">${v._kind} · ${v.type}</span></td><td>${v.from} → ${v.to}</td><td>${v.dep} – ${v.arr}</td><td style="font-weight:700">${fmtMoney(v.price)}</td><td>${v.seats}</td><td><div class="action-btns"><button class="btn btn-blue btn-sm" onclick="editVehicle('${v.id}','${v._kind.toLowerCase()}')">Edit</button><button class="btn btn-danger btn-sm" onclick="deleteVehicle('${v.id}','${v._kind.toLowerCase()}')">Delete</button></div></td></tr>`).join(''); return `<div class="admin-main-title">Trains & Buses</div><div class="admin-main-sub">Manage the vehicle fleet</div><div class="admin-table-wrap"><div class="admin-table-header"><div class="admin-table-title">All Vehicles (${all.length})</div><button class="btn btn-primary btn-sm" onclick="openAddTrain()">+ Add Vehicle</button></div><div style="overflow-x:auto"><table class="admin-table"><thead><tr><th>Number</th><th>Name</th><th>Route</th><th>Timings</th><th>Price</th><th>Seats</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table></div></div>`; }
function adminStations() { const cities = DB.get('cities'); const pills = cities.map((c, i) => `<div style="display:flex;align-items:center;gap:8px;background:var(--panel);border:1.5px solid var(--border);border-radius:10px;padding:10px 14px;box-shadow:var(--sh)"><span>🏙️</span><span style="font-weight:700;font-size:13px;flex:1;color:var(--cream)">${c}</span><button class="btn btn-danger btn-sm" onclick="removeCity(${i})">Remove</button></div>`).join(''); return `<div class="admin-main-title">Stations & Cities</div><div class="admin-main-sub">Manage the city network (${cities.length} cities)</div><div style="display:flex;gap:10px;margin-bottom:20px"><input class="form-input" id="new-city" placeholder="New city name" style="max-width:240px"><button class="btn btn-primary" onclick="addCity()">+ Add City</button></div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px">${pills}</div>`; }
function addCity() { const v = document.getElementById('new-city').value.trim(); if (!v) return; const cities = DB.get('cities'); if (cities.includes(v)) return toast('City already exists', 'error'); cities.push(v); DB.set('cities', cities); toast('City added: ' + v); render(); }
function removeCity(i) { const cities = DB.get('cities'); cities.splice(i, 1); DB.set('cities', cities); toast('City removed'); render(); }
function adminBookings() { const bks = DB.get('bookings'); const users = DB.get('users'); const rows = [...bks].sort((a, b) => b.bookedAt.localeCompare(a.bookedAt)).map(b => { const u = users.find(x => x.id === b.userId); return `<tr><td><code style="font-size:11px;color:var(--muted2)">${b.id}</code></td><td>${u ? u.name : '?'}</td><td>${b.from} → ${b.to}</td><td>${b.vehicleName}</td><td>${fmtDate(b.date)}</td><td>${b.seats.join(', ')}</td><td style="font-weight:700">${fmtMoney(b.total)}</td><td><span class="bi-status status-${b.status}" style="font-size:10px">${b.status}</span></td><td>${b.status === 'confirmed' ? `<button class="btn btn-danger btn-sm" onclick="adminCancelBooking('${b.id}')">Cancel</button>` : ''}</td></tr>`; }).join(''); return `<div class="admin-main-title">All Bookings</div><div class="admin-main-sub">${bks.length} total bookings</div><div class="admin-table-wrap"><div style="overflow-x:auto"><table class="admin-table"><thead><tr><th>ID</th><th>User</th><th>Route</th><th>Vehicle</th><th>Date</th><th>Seats</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div></div>`; }
function adminCancelBooking(id) { DB.update('bookings', id, { status: 'cancelled' }); toast('Booking cancelled'); render(); }
function adminUsers() { const users = DB.get('users'); const bks = DB.get('bookings'); const rows = users.map(u => { const ub = bks.filter(b => b.userId === u.id); const rev = ub.filter(b => b.status !== 'cancelled').reduce((s, b) => s + b.total, 0); return `<tr><td style="font-weight:700">${u.name}</td><td>${u.email}</td><td><span class="tag ${u.role === 'admin' ? 'tag-gold' : 'tag-blue'}">${u.role}</span></td><td>${fmtDate(u.createdAt)}</td><td>${ub.length}</td><td style="font-weight:700">${fmtMoney(rev)}</td><td><span class="bi-status ${u.active !== false ? 'status-confirmed' : 'status-cancelled'}" style="font-size:10px">${u.active !== false ? 'Active' : 'Blocked'}</span></td><td>${u.role !== 'admin' ? `<button class="btn btn-secondary btn-sm" onclick="toggleUserBlock('${u.id}',${u.active !== false})">${u.active !== false ? 'Block' : 'Unblock'}</button>` : '<span style="font-size:11px;color:var(--muted2)">Protected</span>'}</td></tr>`; }).join(''); return `<div class="admin-main-title">Users</div><div class="admin-main-sub">${users.length} accounts registered</div><div class="admin-table-wrap"><div style="overflow-x:auto"><table class="admin-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Joined</th><th>Bookings</th><th>Revenue</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div></div>`; }
function toggleUserBlock(id, isActive) { DB.update('users', id, { active: !isActive }); toast(isActive ? 'User blocked' : 'User unblocked'); render(); }
function renderModal() { return `<div class="modal-overlay" onclick="if(event.target===this)closeModal()"><div class="modal-card"><button class="modal-close" onclick="closeModal()">✕</button>${S.modal}</div></div>`; }
function closeModal() { S.modal = null; render(); }
function openAddTrain() { const cities = DB.get('cities'); const cityOpts = cities.map(c => `<option>${c}</option>`).join(''); S.modal = `<div class="modal-title">Add New Vehicle</div><div class="modal-form"><div class="form-row"><div class="form-group"><label class="form-label">Name</label><input class="form-input" id="m-name" placeholder="Mumbai Express"></div><div class="form-group"><label class="form-label">Number</label><input class="form-input" id="m-num" placeholder="12101"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Type</label><select class="form-input" id="m-type"><option value="express">Express Train</option><option value="superfast">Superfast Train</option><option value="regular">Regular Train</option><option value="bus-ac">AC Bus</option><option value="bus-normal">Normal Bus</option><option value="flight-economy">Economy Flight</option><option value="flight-business">Business Flight</option></select></div><div class="form-group"><label class="form-label">Seats</label><input class="form-input" type="number" id="m-seats" value="56"></div></div><div class="form-row"><div class="form-group"><label class="form-label">From</label><select class="form-input" id="m-from">${cityOpts}</select></div><div class="form-group"><label class="form-label">To</label><select class="form-input" id="m-to">${cityOpts}</select></div></div><div class="form-row"><div class="form-group"><label class="form-label">Departs</label><input class="form-input" type="time" id="m-dep" value="06:00"></div><div class="form-group"><label class="form-label">Arrives</label><input class="form-input" type="time" id="m-arr" value="09:00"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Price (₹)</label><input class="form-input" type="number" id="m-price" value="350"></div><div class="form-group"><label class="form-label">Safety (1-10)</label><input class="form-input" type="number" id="m-safety" value="8.5" step="0.1" min="1" max="10"></div></div><div class="form-group"><label class="form-label">Via stops (comma-separated)</label><input class="form-input" id="m-via" placeholder="Lonavala, Talegaon"></div><div class="modal-actions"><button class="btn btn-primary" onclick="saveVehicle()">Add Vehicle</button><button class="btn btn-secondary" onclick="closeModal()">Cancel</button></div></div>`; render(); }
function saveVehicle() { const type = document.getElementById('m-type').value; let kind = 'trains'; if(type.startsWith('bus')) kind = 'buses'; if(type.startsWith('flight')) kind = 'airplanes'; const dep = document.getElementById('m-dep').value; const arr = document.getElementById('m-arr').value; const depM = timeToMins(dep), arrM = timeToMins(arr); const duration = arrM >= depM ? arrM - depM : (1440 - depM) + arrM; const v = { id: uid(), name: document.getElementById('m-name').value, number: document.getElementById('m-num').value, type, from: document.getElementById('m-from').value, to: document.getElementById('m-to').value, via: document.getElementById('m-via').value.split(',').map(s => s.trim()).filter(Boolean), dep, arr, duration, price: +document.getElementById('m-price').value, safety: +document.getElementById('m-safety').value, seats: +document.getElementById('m-seats').value }; DB.add(kind, v); closeModal(); toast('Vehicle added!'); }
function editVehicle(id, kind) { const key = kind === 'train' ? 'trains' : kind === 'bus' ? 'buses' : 'airplanes'; const v = DB.find(key, x => x.id === id); if (!v) return; S.modal = `<div class="modal-title">Edit Vehicle</div><div class="modal-form"><div class="form-row"><div class="form-group"><label class="form-label">Name</label><input class="form-input" id="e-name" value="${v.name}"></div><div class="form-group"><label class="form-label">Number</label><input class="form-input" id="e-num" value="${v.number}"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Price (₹)</label><input class="form-input" type="number" id="e-price" value="${v.price}"></div><div class="form-group"><label class="form-label">Safety</label><input class="form-input" type="number" id="e-safety" value="${v.safety}" step="0.1"></div></div><div class="form-row"><div class="form-group"><label class="form-label">Departs</label><input class="form-input" type="time" id="e-dep" value="${v.dep}"></div><div class="form-group"><label class="form-label">Arrives</label><input class="form-input" type="time" id="e-arr" value="${v.arr}"></div></div><div class="form-group"><label class="form-label">Seats</label><input class="form-input" type="number" id="e-seats" value="${v.seats}"></div><div class="modal-actions"><button class="btn btn-primary" onclick="updateVehicle('${id}','${kind}')">Save Changes</button><button class="btn btn-secondary" onclick="closeModal()">Cancel</button></div></div>`; render(); }
function updateVehicle(id, kind) { const key = kind === 'train' ? 'trains' : kind === 'bus' ? 'buses' : 'airplanes'; const dep = document.getElementById('e-dep').value; const arr = document.getElementById('e-arr').value; const depM = timeToMins(dep), arrM = timeToMins(arr); const duration = arrM >= depM ? arrM - depM : (1440 - depM) + arrM; DB.update(key, id, { name: document.getElementById('e-name').value, number: document.getElementById('e-num').value, price: +document.getElementById('e-price').value, safety: +document.getElementById('e-safety').value, seats: +document.getElementById('e-seats').value, dep, arr, duration }); closeModal(); toast('Vehicle updated!'); }
function deleteVehicle(id, kind) { const key = kind === 'train' ? 'trains' : kind === 'bus' ? 'buses' : 'airplanes'; DB.remove(key, id); toast('Vehicle removed'); render(); }
function timeToMins(t) { const [h, m] = t.split(':').map(Number); return h * 60 + m; }
if (typeof initDB === 'function') initDB();
restoreSession();
if (S.user && S.user.role === 'admin') S.view = 'admin';
render();